title: "Game Theory and Mechanism Design with Large Language Models"
description: "Workshop at ACM EC 2026"
url: "https://indraos.github.io"
baseurl: "/llm-incentives"
markdown: kramdown
plugins:
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor
